spring:
  config:
    import:
      - optional:classpath:secret/db.yml
      - optional:classpath:secret/auth.yml
  application:
    name: workspaces_club
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect
    properties:
      hibernate:
        format_sql: true
  thymeleaf:
    cache: false
logging:
  level:
    org.springframework.security.web: trace
    com.levelupseon: debug
  profiles:
    include = oauth



